_wandb:
    value:
        cli_version: 0.24.0
        e:
            x2t1d7mm6i7q1dab2ejgr82mcue0mzs5:
                args:
                    - config/train_vanilla_6L_12H.py
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1916622938112"
                        used: "92732014592"
                email: matan13av@gmail.com
                executable: /home/nlp/matan_avitan/.conda/envs/b200/bin/python
                git:
                    commit: 3adf61e154c3fe3fca428ad6bc3818b27a3b8291
                    remote: https://github.com/karpathy/nanoGPT.git
                gpu: NVIDIA B200
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-519b2b5b-dab4-6473-a2b5-7630f94c2f29
                host: dgx-b200-01
                memory:
                    total: "2163650633728"
                os: Linux-5.14.0-570.60.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /home/nlp/matan_avitan/git/no_mlp_exp/nanoGPT/train.py
                python: CPython 3.12.12
                root: /home/nlp/matan_avitan/git/no_mlp_exp/nanoGPT
                slurm:
                    cluster_name: slurm-biu
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: ug_goldberg
                    job_cpus_per_node: "8"
                    job_end_time: "1770033288"
                    job_gid: "1301"
                    job_gpus: "3"
                    job_id: "3001129"
                    job_name: vanilla_gpt
                    job_nodelist: dgx-b200-01
                    job_num_nodes: "1"
                    job_partition: p_b200_nlp
                    job_qos: normal
                    job_start_time: "1770018888"
                    job_uid: "30607"
                    job_user: matan_avitan
                    jobid: "3001129"
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dgx-b200-01
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    restart_count: "2"
                    submit_dir: /home/nlp/matan_avitan/git/no_mlp_exp
                    submit_host: slurm-login3
                    task_pid: "2352888"
                    tasks_per_node: "1"
                    topology_addr: dgx-b200-01
                    topology_addr_pattern: node
                    tres_per_task: cpu=8
                startedAt: "2026-02-02T07:54:57.754416Z"
                writerId: x2t1d7mm6i7q1dab2ejgr82mcue0mzs5
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 12
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 1024
compile:
    value: true
dataset:
    value: openwebtext
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0
dtype:
    value: bfloat16
eval_interval:
    value: 2000
eval_iters:
    value: 200
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 40
init_from:
    value: scratch
learning_rate:
    value: 0.0006
log_interval:
    value: 1
lr_decay_iters:
    value: 600000
max_iters:
    value: 600000
min_lr:
    value: 6e-05
n_embd:
    value: 768
n_head:
    value: 12
n_layer:
    value: 6
out_dir:
    value: out_vanilla_6L_12H
use_no_mlp:
    value: false
value_dim:
    value: null
wandb_log:
    value: true
wandb_project:
    value: no_mlp_exp
wandb_run_name:
    value: vanilla_6L_12H_baseline
warmup_iters:
    value: 2000
weight_decay:
    value: 0.1
